### ISSUE TITLE
Prueba de librerías en Proyecto

### ISSUE THREAD

**Issue by javierchaz234** [aigora/twE105_1920-los_chispas#8]
@oscarperpinan  he creado un proyecto para probar la unión de todos los juegos pero no se si estoy utilizando la librería de forma adecuada podría echarle un vistazo cuando tenga tiempo para saber en que me equivoco por favor. Se trata de la carpeta proyecto dentro de la carpeta trabajo y es la prueba con una copia de mi propio juego ahorcado. Muchas gracias y un saludo.

**Comment by oscarperpinan** [comment]
Por lo que veo, la librería está bien definida  y la cabecera bien incluida en los dos ficheros .c. ¿Cuál es el problema que tenéis?

Si es un problema al compilar con DevC++, os sugiero que utilicéis otra IDE diferente, que es más amigable para estas tareas: [Code::Blocks](http://www.codeblocks.org/). Mirad su documentación para ver [cómo crear un proyecto](http://wiki.codeblocks.org/index.php/Creating_a_new_project).
